### ISSUE TITLE
博文下read more按钮失效，变成一个文本而不是超链接

### ISSUE THREAD

**Issue by HanMufu** [FromEndWorld/LOFFER#22]
Hi FromEndWorld, 感谢你制作了这份模版，非常好用，使用指南也写得很清楚，感谢。
我现在遇到了一个问题：发表了一篇新写的博文之后，我发现这篇博文下面read more按钮失效变成了一个文本。我搜索了代码在index.html里看到拼接read more url的部分，但是没有看出来引起这个问题的原因。请问一下应该怎么解决呢？谢谢
该博文md文件链接：https://github.com/HanMufu/home/blob/master/_posts/2020-03-27-Example-code-for-using-AWS-SNS-Service-in-Java.md
博客链接：https://hanmufu.github.io/home/

**Comment by FromEndWorld** [comment]
你好，这通常是因为自动截取摘要失败，然后截取到的摘要混进了一些代码，请在你的第一段落后添加一个手动截取摘要的标记 `<!-- more -->`

**Comment by HanMufu** [comment]
完美解决，谢谢
