### ISSUE TITLE
LaTex未显示

### ISSUE THREAD

**Issue by jianqiaomo** [FromEndWorld/LOFFER#26]
![QQ拼音截图20200810232922](https://user-images.githubusercontent.com/53131608/89800698-b26cb200-db61-11ea-9cf6-d061c465c57c.png)
感谢博主提供的模版！
但是我在测试你的LaTex时，打开《LaTex渲染的说明和测试》发现没有正常显示，请问是什么情况呢？谢谢

**Comment by FromEndWorld** [comment]
谢谢告知……暂时还没搞清是什么状况

**Comment by FromEndWorld** [comment]
修好了……我六月份莫名给它改坏了，完全不记得自己为啥这么做orz
