### ISSUE TITLE
手机端的无法显示图片

### ISSUE THREAD

**Issue by roulan2000** [FromEndWorld/LOFFER#34]
我发现使用手机或者ipad打开博客，都会出现图片显示问题。以{{ site.baseurl }}/images/xxx.jpg的形式插入的图片可以正常显示（如我在自己在404页面插入的图片），但直接通过图片地址https://...之类插入的图片在手机端无法正常显示（如LOFFER博文中的图片）。我让朋友用手机查看了一下也是一样的情况。
另外头像图片是通过_config.yml中的avatar设置的，这里不能用{{ site.baseurl }}/images/xxx.jpg的形式插入图片，我暂时没有找到让它正常显示的方法。

**Comment by FromEndWorld** [comment]
你好，我这里手机端一切正常啊

**Comment by roulan2000** [comment]
已经解决了，是dns的问题。另外_config.yml中的avatar:后面可以直接输入/images/xxx.jpg，这样能正常显示头像和小图标。
