### ISSUE TITLE
toc 目录解析层级问题

### ISSUE THREAD

**Issue by bigwolftime** [FromEndWorld/LOFFER#37]
https://gitee.com/index1024/xblog/blob/master/_posts/2021-04-10-strategy-design-pattern.md

这个是某一篇的blog的源代码，其部署解析后的目录层级出现了问题(其中的 *三. 其他*, *四. 参考* 的层级解析有误)

![TOC解析](https://zonheng.net/toc_parse_problem.png)

**Comment by FromEndWorld** [comment]
<https://github.com/allejo/jekyll-toc> 试试安装这个toc插件的最新版
