### ISSUE TITLE
很棒的主题，希望有机会可以添加 目录 TOC 支持

### ISSUE THREAD

**Issue by waizeiaifu** [FromEndWorld/LOFFER#5]
看了那么多主题，个人感觉这个是最棒的，唯一遗憾的就是 post 没有目录，如果添加目录支持就完美了

**Comment by FromEndWorld** [comment]
谢谢， 好的，下一步试试加个TOC

**Comment by FromEndWorld** [comment]
TOC添上了，虽然是个不会折叠的静态目录

**Comment by waizeiaifu** [comment]
我试用了一下，很棒，提个建议，目录可以排在右边，布局会好看一些，不知道你怎么看，[效果](https://xiaoye220.github.io/Command-Line-Tool/)。还有那个人工智障的问题有办法解决吗。。😂😂
