### ISSUE TITLE
在Gitee Pages上无法使用你的主题

### ISSUE THREAD

**Issue by laomocode** [FromEndWorld/LOFFER#6]
你好，作者同志。我为了加快网站的浏览速度，特意把你的博客主题搞到了[码云（GItee）](https://gitee.com)上面，用码云的Pages服务来建博客。但是无法正常打开，提示部署失败，日志：
`错误信息: Invalid CSS after "...kground-color: ": expected expression (e.g. 1px, bold), was "#868e961a;" on line 64`
那么，现在该怎么办？

**Comment by FromEndWorld** [comment]
你好，看起来有可能是因为我用了带透明度的8位HEX颜色……
可以试试到_variables.scss 文件里把相应的颜色改成无透明度颜色，或者rgba/hsla格式。
我有机会想办法优化一下，8位HEX颜色支持度确实不高，不过我对码云没什么了解，如果有其他问题应该很难帮到你。

**Comment by laomocode** [comment]
还真的可以了可以了，希望作者大大发布更新

**Comment by laomocode** [comment]
但我早就因为这个原因去重头做起自己的博客了😂
